-- ==========================================================
-- WARNING: Auto-generated schema. Review before using in production.
-- ==========================================================
-- Generated by IdeiaEstruturada from Idea Pack
-- Project: Gestão Pedagógica — Gestão de Infraestrutura
-- Generated at: 2026-03-15T21:47:14.395Z
-- Entities: 3
-- ==========================================================

-- Trigger function for updated_at
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- Table: predios (from Entity: Prédio)
-- Representa edifícios ou blocos dentro da unidade escolar
-- ============================================
CREATE TABLE IF NOT EXISTS predios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL -- Nome do prédio,
  endereco TEXT -- Localização física,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER set_predios_updated_at
  BEFORE UPDATE ON predios
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();

-- ============================================
-- Table: ambientes (from Entity: Ambiente)
-- Espaços físicos dentro dos prédios, como salas e laboratórios
-- ============================================
CREATE TABLE IF NOT EXISTS ambientes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  predio_id UUID NOT NULL REFERENCES predios(id) ON DELETE CASCADE,
  recurso_id UUID NOT NULL REFERENCES recursos(id) ON DELETE CASCADE,
  nome TEXT NOT NULL -- Nome do ambiente,
  tipo TEXT NOT NULL -- Tipo de ambiente (sala de aula, laboratório, auditório, oficina),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ambientes_predio ON ambientes(predio_id);
CREATE INDEX IF NOT EXISTS idx_ambientes_recurso ON ambientes(recurso_id);

CREATE TRIGGER set_ambientes_updated_at
  BEFORE UPDATE ON ambientes
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();

-- ============================================
-- Table: recursos (from Entity: Recurso)
-- Itens disponíveis nos ambientes que definem sua funcionalidade
-- ============================================
CREATE TABLE IF NOT EXISTS recursos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL -- Nome do recurso,
  quantidade NUMERIC NOT NULL -- Quantidade disponível,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER set_recursos_updated_at
  BEFORE UPDATE ON recursos
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();


-- ============================================
-- WARNINGS — Missing Entity References
-- ============================================
-- ⚠️ Entity "Recurso" references "Disciplina" but "Disciplina" is not defined as an Entity in the scope. Create this entity or remove the relationship.
-- Fix: Create the missing entities in the discovery or remove the relationships.
